import "./globals.css";
import Nav from "@/components/Nav";
import { PokemonProvider } from "@/hooks/usePokemonApi";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
        <PokemonProvider>
          <Nav />
          {children}
        </PokemonProvider>
      </body>
    </html>
  );
}
